create table if not exists hospital.edge_request_counters (
  id bigint generated by default as identity primary key,
  scope text not null,
  subject text not null,
  window_start timestamptz not null,
  request_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (scope, subject, window_start)
);

create table if not exists hospital.edge_audit_logs (
  id bigint generated by default as identity primary key,
  function_name text not null,
  endpoint text not null,
  action text not null,
  actor_user_id uuid,
  actor_role text,
  request_ip text,
  request_id text,
  status_code integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists hospital.edge_error_logs (
  id bigint generated by default as identity primary key,
  function_name text not null,
  endpoint text not null,
  actor_user_id uuid,
  request_ip text,
  request_id text,
  error_message text not null,
  error_stack text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_edge_request_counters_scope_subject_window on hospital.edge_request_counters (scope, subject, window_start desc);
create index if not exists idx_edge_audit_logs_created_at on hospital.edge_audit_logs (created_at desc);
create index if not exists idx_edge_audit_logs_function_endpoint on hospital.edge_audit_logs (function_name, endpoint);
create index if not exists idx_edge_error_logs_created_at on hospital.edge_error_logs (created_at desc);
create index if not exists idx_edge_error_logs_function_endpoint on hospital.edge_error_logs (function_name, endpoint);

drop trigger if exists trg_edge_request_counters_updated_at on hospital.edge_request_counters;
create trigger trg_edge_request_counters_updated_at
before update on hospital.edge_request_counters
for each row execute function hospital.set_updated_at();

alter table hospital.edge_request_counters enable row level security;
alter table hospital.edge_audit_logs enable row level security;
alter table hospital.edge_error_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'hospital' and tablename = 'edge_request_counters' and policyname = 'edge_request_counters_admin_select'
  ) then
    create policy edge_request_counters_admin_select
      on hospital.edge_request_counters
      for select
      to public
      using (hospital.is_admin());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'hospital' and tablename = 'edge_audit_logs' and policyname = 'edge_audit_logs_admin_select'
  ) then
    create policy edge_audit_logs_admin_select
      on hospital.edge_audit_logs
      for select
      to public
      using (hospital.is_admin());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'hospital' and tablename = 'edge_error_logs' and policyname = 'edge_error_logs_admin_select'
  ) then
    create policy edge_error_logs_admin_select
      on hospital.edge_error_logs
      for select
      to public
      using (hospital.is_admin());
  end if;
end
$$;

create or replace function hospital.consume_rate_limit(
  p_scope text,
  p_subject text,
  p_max_requests integer,
  p_window_seconds integer default 60
)
returns table (
  allowed boolean,
  requests_used integer,
  reset_at timestamptz
)
language plpgsql
security definer
set search_path = hospital, public
as $$
declare
  v_now timestamptz := now();
  v_window_start timestamptz;
  v_count integer;
begin
  if p_scope is null or p_subject is null or p_max_requests is null or p_window_seconds is null then
    raise exception 'invalid_rate_limit_input';
  end if;

  v_window_start := to_timestamp(floor(extract(epoch from v_now) / p_window_seconds) * p_window_seconds);

  insert into hospital.edge_request_counters as rc (scope, subject, window_start, request_count)
  values (p_scope, p_subject, v_window_start, 1)
  on conflict (scope, subject, window_start)
  do update set request_count = rc.request_count + 1
  returning rc.request_count into v_count;

  allowed := v_count <= p_max_requests;
  requests_used := v_count;
  reset_at := v_window_start + make_interval(secs => p_window_seconds);

  return next;
end;
$$;

revoke all on function hospital.consume_rate_limit(text, text, integer, integer) from public;
grant execute on function hospital.consume_rate_limit(text, text, integer, integer) to anon, authenticated, service_role;

do $$
declare
  v_province_id bigint;
  v_city_id bigint;
begin
  if not exists (select 1 from hospital.provinces where name = 'Metro Manila') then
    insert into hospital.provinces (name) values ('Metro Manila') returning id into v_province_id;
  else
    select id into v_province_id from hospital.provinces where name = 'Metro Manila' limit 1;
  end if;

  if not exists (select 1 from hospital.cities where name = 'Quezon City') then
    insert into hospital.cities (province_id, name) values (v_province_id, 'Quezon City') returning id into v_city_id;
  else
    select id into v_city_id from hospital.cities where name = 'Quezon City' limit 1;
  end if;

  if not exists (select 1 from hospital.facilities where id = '11111111-1111-1111-1111-111111111111') then
    insert into hospital.facilities (id, name, level, status)
    values ('11111111-1111-1111-1111-111111111111', 'Metropolitan Medical Center', 'tertiary', 'approved');
  end if;

  if not exists (select 1 from hospital.facilities where id = '22222222-2222-2222-2222-222222222222') then
    insert into hospital.facilities (id, name, level, status)
    values ('22222222-2222-2222-2222-222222222222', 'City Medical Clinic', 'secondary', 'pending');
  end if;

  insert into hospital.facility_addresses (facility_id, address_line, barangay, city_id, postal_code, latitude, longitude)
  values ('11111111-1111-1111-1111-111111111111', '123 Health Ave', 'Bagumbayan', v_city_id, '1110', 14.6760, 121.0437)
  on conflict (facility_id) do update set
    address_line = excluded.address_line,
    barangay = excluded.barangay,
    city_id = excluded.city_id,
    postal_code = excluded.postal_code,
    latitude = excluded.latitude,
    longitude = excluded.longitude;

  insert into hospital.facility_addresses (facility_id, address_line, barangay, city_id, postal_code, latitude, longitude)
  values ('22222222-2222-2222-2222-222222222222', '456 Wellness St', 'Commonwealth', v_city_id, '1121', 14.7000, 121.0780)
  on conflict (facility_id) do update set
    address_line = excluded.address_line,
    barangay = excluded.barangay,
    city_id = excluded.city_id,
    postal_code = excluded.postal_code,
    latitude = excluded.latitude,
    longitude = excluded.longitude;

  insert into hospital.facility_contacts (facility_id, kind, phone_number, is_primary)
  values ('11111111-1111-1111-1111-111111111111', 'main', '(02) 8111-2222', true)
  on conflict (facility_id, kind, phone_number) do nothing;

  insert into hospital.facility_contacts (facility_id, kind, phone_number, is_primary)
  values ('11111111-1111-1111-1111-111111111111', 'emergency', '(02) 8111-3333', false)
  on conflict (facility_id, kind, phone_number) do nothing;

  insert into hospital.facility_contacts (facility_id, kind, phone_number, is_primary)
  values ('22222222-2222-2222-2222-222222222222', 'main', '(02) 8222-4444', true)
  on conflict (facility_id, kind, phone_number) do nothing;

  insert into hospital.facility_operating_hours (facility_id, day_of_week, opens_at, closes_at, is_closed)
  values
    ('11111111-1111-1111-1111-111111111111', 1, '08:00', '17:00', false),
    ('11111111-1111-1111-1111-111111111111', 2, '08:00', '17:00', false),
    ('11111111-1111-1111-1111-111111111111', 3, '08:00', '17:00', false),
    ('11111111-1111-1111-1111-111111111111', 4, '08:00', '17:00', false),
    ('11111111-1111-1111-1111-111111111111', 5, '08:00', '17:00', false),
    ('11111111-1111-1111-1111-111111111111', 6, '08:00', '12:00', false),
    ('11111111-1111-1111-1111-111111111111', 0, null, null, true)
  on conflict (facility_id, day_of_week) do update set
    opens_at = excluded.opens_at,
    closes_at = excluded.closes_at,
    is_closed = excluded.is_closed;

  insert into hospital.facility_services (facility_id, service_id, available)
  select '11111111-1111-1111-1111-111111111111', sc.id, (sc.code in ('er_24_7', 'maternity', 'xray'))
  from hospital.service_catalog sc
  on conflict (facility_id, service_id) do update set available = excluded.available;

  insert into hospital.facility_services (facility_id, service_id, available)
  select '22222222-2222-2222-2222-222222222222', sc.id, (sc.code in ('xray', 'laboratory'))
  from hospital.service_catalog sc
  on conflict (facility_id, service_id) do update set available = excluded.available;
end
$$;
